/*** GENERATED BY @bugsounet MMM-GoogleAssistant v6.2.4 ***/
/*** https://forum.bugsounet.fr **/

var config = {
  address: 'localhost',
  port: 8080,
  basePath: '/',
  ipWhitelist: [
    '127.0.0.1',
    '::ffff:127.0.0.1',
    '::1'
  ],
  useHttps: false,
  httpsPrivateKey: '',
  httpsCertificate: '',
  language: 'en',
  locale: 'en-US',
  logLevel: [
    'INFO',
    'LOG',
    'WARN',
    'ERROR'
  ],
  timeFormat: 24,
  units: 'metric',
  modules: [
    {
      module: 'MMM-GoogleAssistant',
      configDeepMerge: true,
      config: {
        assistantConfig: {
          latitude: 51.50853,
          longitude: -0.076132
        },
        recipes:[
        'recipe.js'
        ],
        website: {
          use: true,
          username: 'odin',
          password: 'odin',
          CLIENT_ID: null
        }
      }
    },
    {
 module: 'MMM-GmailFeed',
 position: 'bottom_bar',
 config: {
  username: 'tgraj29@gmail.com',
  password: 'muxq xzxt iaxt kkdg',
  updateInterval: 60000,
  maxEmails: 5,
  maxSubjectLength: 38,
  maxFromLength: 15,
  playSound: true,
  autoHide: true,
  displayMode: "table",
 }
},
    {
      module: 'EXT-Detector',
      position: 'top_left',
      disabled: false,
      configDeepMerge: true,
      config: {
        debug: false,
        useIcon: true,
        detectors: [
          {
            detector: 'Snowboy',
            Model: 'jarvis',
            Sensitivity: null
          },
          {
            detector: 'Snowboy',
            Model: 'ok google',
            Sensitivity: null
          },
          {
            detector: 'Snowboy',
            Model: 'hey google',
            Sensitivity: null
          }
        ]
      }
    },
    {
      module: 'MMM-RAIN-MAP',
      position: 'bottom_right',
      config: {
        animationSpeedMs: 400,
        colorScheme: 2,
        colorizeTime: true,
        defaultZoomLevel: 8,
        displayTime: true,
        displayTimeline: true,
        displayClockSymbol: true,
        displayHoursBeforeRain: -1,
        extraDelayLastFrameMs: 1000,
        extraDelayCurrentFrameMs: 3000,
        invertColors: false,
        markers: [
          {
            lat: 49.41,
            lng: 8.717,
            color: 'red'
          },
          {
            lat: 48.856,
            lng: 2.35,
            color: 'green'
          }
        ],
        mapPositions: [
          {
            lat: 49.41,
            lng: 8.717,
            zoom: 9,
            loops: 1
          },
          {
            lat: 49.41,
            lng: 8.717,
            zoom: 6,
            loops: 2
          },
          {
            lat: 48.856,
            lng: 2.35,
            zoom: 6,
            loops: 1
          },
          {
            lat: 48.856,
            lng: 2.35,
            zoom: 9,
            loops: 2
          },
          {
            lat: 49.15,
            lng: 6.154,
            zoom: 5,
            loops: 2
          }
        ],
        mapUrl: 'https://a.tile.openstreetmap.de/{z}/{x}/{y}.png',
        mapHeight: '280px',
        mapWidth: '280px',
        maxHistoryFrames: -1,
        maxForecastFrames: -1,
        substitudeModules: [],
        updateIntervalInSeconds: 300
      }
    },
    {
      module: 'alert'
    },
    {
      module: 'updatenotification',
      position: 'top_bar'
    },
    {
      module: 'clock',
      position: 'top_left'
    },
    {
      module: 'calendar',
      header: 'US Holidays',
      position: 'top_left',
      config: {
        calendars: [
          {
            fetchInterval: 604800000,
            symbol: 'calendar-check',
            url: 'https://ics.calendarlabs.com/76/mm3137/US_Holidays.ics'
          }
        ]
      }
    },
    {
      module: 'compliments',
      position: 'lower_third'
    },
    {
      module: 'newsfeed',
      position: 'bottom_bar',
      config: {
        feeds: [
          {
            title: 'New York Times',
            url: 'https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml'
          }
        ],
        showSourceTitle: true,
        showPublishDate: true,
        broadcastNewsFeeds: true,
        broadcastNewsUpdates: true
      }
    },
    {
      module: 'MMM-Screencast',
      position: 'top_center',
      config: {
        position: 'topCenter',
        height: 450,
        width: 600,
      }
    },
    
    {
      module: 'EXT-Alert',
      disabled: false,
      config: {
        debug: false,
        style: 1,
        ignore: []
      }
    },
    {
      module: 'EXT-Touch',
      position: 'top_right',
      disabled: false
    },
    {
      module: 'EXT-Welcome',
      disabled: false,
      config: {
        welcome: ''
      }
    },
    {
      module: "MMM-Flights",
      position: "top_left",
      config: {
        laMin: 50.0,
        laMax: 50.21,
        loMin: 8.4,
        loMax: 8.8,
      },
    },
    {
      module: 'MMM-TuyaSL',
      position: 'top_right',
      header: 'TuyaSL',
      config: {
        userName: 'tgraj29@gmail.com',
        password: 'CLASHof1!',
        countryCode: 'US',
        showOnlyOnline: true,
        showOnlyOn: false,
        colour: false,
        updateInterval: 300 * 1000,
        timeout: 10 * 1000,
      }
    },

    {
      module: 'EXT-Pages',
      position: 'bottom_bar',
      disabled: false,
      config: {
        pages: {
          '0': [
            'newsfeed',
            'clock',
            'MMM-GoogleAssistant',
            'EXT-Detector',
            'compliments',
            'calendar',
           
          ],
          '1': [
            'clock',
            'MMM-GmailFeed',
            'MMM-Screencast',
            'MMM-TuyaSL'
            
          ],
          '2':[
            'clock',
            'MMM-RAIN-MAP',
            'MMM-Flights'
          ],
          fixed: [
            'clock',
            'MMM-GoogleAssistant',
            'EXT-Detector',
            'calendar'
          ],
          hiddenPages: {},
          animationTime: 1000
        },
        rotationTime: 0,
        rotationTimes: {},
        homePage: 0,
        indicator: true,
        hideBeforeRotation: false,
        Gateway: {},
        loading: 'loading.png'
      }
    }
  ]
}

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== 'undefined') {module.exports = config;}
